### ISSUE TITLE
Resource update failing

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/data-importer#16]
When running dataset task, updating resource with new last_modified fails. 

Stacktrace:

<code>
[Wed Sep 27 12:44:09.871681 2017] [:error] [pid 70494:tid 140372650989312] Traceback (most recent call last):
[Wed Sep 27 12:44:09.871685 2017] [:error] [pid 70494:tid 140372650989312]   File "/usr/lib/ckan/default/src/ckan/ckan/model/modification.py", line 79, in notify
[Wed Sep 27 12:44:09.871688 2017] [:error] [pid 70494:tid 140372650989312]     observer.notify(entity, operation)
[Wed Sep 27 12:44:09.871690 2017] [:error] [pid 70494:tid 140372650989312]   File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 114, in notify
[Wed Sep 27 12:44:09.871693 2017] [:error] [pid 70494:tid 140372650989312]     for resource in entity.resources:
[Wed Sep 27 12:44:09.871695 2017] [:error] [pid 70494:tid 140372650989312]   File "/usr/lib/ckan/default/src/ckan/ckan/model/package.py", line 91, in resources
[Wed Sep 27 12:44:09.871699 2017] [:error] [pid 70494:tid 140372650989312]     assert len(self.resource_groups_all) == 1, "can only use resources on packages if there is only one resource_group"
[Wed Sep 27 12:44:09.871701 2017] [:error] [pid 70494:tid 140372650989312] AssertionError: can only use resources on packages if there is only one resource_group
[Wed Sep 27 12:44:09.921575 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399] mod_wsgi (pid=70494): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Wed Sep 27 12:44:09.921756 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399] Traceback (most recent call last):
[Wed Sep 27 12:44:09.921791 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/middleware.py", line 201, in __call__
[Wed Sep 27 12:44:09.922320 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     self.app, environ, catch_exc_info=True)
[Wed Sep 27 12:44:09.922349 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
[Wed Sep 27 12:44:09.922373 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     app_iter = application(environ, start_response)
[Wed Sep 27 12:44:09.922386 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/raven/middleware.py", line 98, in __call__
[Wed Sep 27 12:44:09.922398 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     iterable = self.application(environ, start_response)
[Wed Sep 27 12:44:09.922406 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 382, in __call__
[Wed Sep 27 12:44:09.922418 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return self.app(environ, start_response)
[Wed Sep 27 12:44:09.922426 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
[Wed Sep 27 12:44:09.922455 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return self.apps[-1](environ, start_response)
[Wed Sep 27 12:44:09.922467 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 246, in __call__
[Wed Sep 27 12:44:09.922477 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return self.app(environ, start_response)
[Wed Sep 27 12:44:09.922485 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
[Wed Sep 27 12:44:09.922495 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     app_iter = self.application(environ, start_response)
[Wed Sep 27 12:44:09.922501 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 107, in __call__
[Wed Sep 27 12:44:09.922513 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     app_iter = app(environ, wrapper.wrap_start_response)
[Wed Sep 27 12:44:09.922519 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Wed Sep 27 12:44:09.922528 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     resp = self.call_func(req, *args, **self.kwargs)
[Wed Sep 27 12:44:09.922536 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Wed Sep 27 12:44:09.922545 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return self.func(req, *args, **kwargs)
[Wed Sep 27 12:44:09.922552 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
[Wed Sep 27 12:44:09.922566 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return request.get_response(self.app)
[Wed Sep 27 12:44:09.922572 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Wed Sep 27 12:44:09.922583 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     application, catch_exc_info=False)
[Wed Sep 27 12:44:09.922589 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Wed Sep 27 12:44:09.922606 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     app_iter = application(self.environ, start_response)
[Wed Sep 27 12:44:09.922612 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Wed Sep 27 12:44:09.922625 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     resp = self.call_func(req, *args, **self.kwargs)
[Wed Sep 27 12:44:09.922630 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Wed Sep 27 12:44:09.922638 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return self.func(req, *args, **kwargs)
[Wed Sep 27 12:44:09.922648 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
[Wed Sep 27 12:44:09.922684 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     response = request.get_response(self.app)
[Wed Sep 27 12:44:09.922698 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Wed Sep 27 12:44:09.922709 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     application, catch_exc_info=False)
[Wed Sep 27 12:44:09.922717 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Wed Sep 27 12:44:09.922725 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     app_iter = application(self.environ, start_response)
[Wed Sep 27 12:44:09.922731 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py", line 73, in __call__
[Wed Sep 27 12:44:09.922760 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return self.app(environ, start_response)
[Wed Sep 27 12:44:09.922791 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
[Wed Sep 27 12:44:09.922808 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return self.wrap_app(environ, session_start_response)
[Wed Sep 27 12:44:09.922814 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/routes/middleware.py", line 131, in __call__
[Wed Sep 27 12:44:09.922928 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     response = self.app(environ, start_response)
[Wed Sep 27 12:44:09.923022 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py", line 125, in __call__
[Wed Sep 27 12:44:09.923107 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     response = self.dispatch(controller, environ, start_response)
[Wed Sep 27 12:44:09.923181 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py", line 324, in dispatch
[Wed Sep 27 12:44:09.923265 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return controller(environ, start_response)
[Wed Sep 27 12:44:09.923340 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/controllers/api.py", line 83, in __call__
[Wed Sep 27 12:44:09.923428 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     result = base.BaseController.__call__(self, environ, start_response)
[Wed Sep 27 12:44:09.923503 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 346, in __call__
[Wed Sep 27 12:44:09.923595 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     res = WSGIController.__call__(self, environ, start_response)
[Wed Sep 27 12:44:09.923664 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py", line 221, in __call__
[Wed Sep 27 12:44:09.923743 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     response = self._dispatch_call()
[Wed Sep 27 12:44:09.923824 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py", line 172, in _dispatch_call
[Wed Sep 27 12:44:09.923903 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     response = self._inspect_call(func)
[Wed Sep 27 12:44:09.923974 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py", line 107, in _inspect_call
[Wed Sep 27 12:44:09.924050 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     result = self._perform_call(func, args)
[Wed Sep 27 12:44:09.924118 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py", line 60, in _perform_call
[Wed Sep 27 12:44:09.924186 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return func(**args)
[Wed Sep 27 12:44:09.924257 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/controllers/api.py", line 205, in action
[Wed Sep 27 12:44:09.924335 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     result = function(context, request_data)
[Wed Sep 27 12:44:09.924410 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 414, in wrapped
[Wed Sep 27 12:44:09.924491 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     result = _action(context, data_dict, **kw)
[Wed Sep 27 12:44:09.924556 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/update.py", line 242, in resource_update
[Wed Sep 27 12:44:09.924631 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     model.repo.commit()
[Wed Sep 27 12:44:09.924691 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/vdm/sqlalchemy/tools.py", line 102, in commit
[Wed Sep 27 12:44:09.924765 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     self.session.commit()
[Wed Sep 27 12:44:09.924828 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 114, in do
[Wed Sep 27 12:44:09.924917 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     return getattr(self.registry(), name)(*args, **kwargs)
[Wed Sep 27 12:44:09.924989 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 656, in commit
[Wed Sep 27 12:44:09.925062 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     self.transaction.commit()
[Wed Sep 27 12:44:09.925129 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 314, in commit
[Wed Sep 27 12:44:09.925208 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     self._prepare_impl()
[Wed Sep 27 12:44:09.925288 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 290, in _prepare_impl
[Wed Sep 27 12:44:09.925372 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     self.session.dispatch.before_commit(self.session)
[Wed Sep 27 12:44:09.925444 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/event.py", line 291, in __call__
[Wed Sep 27 12:44:09.925550 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     fn(*args, **kw)
[Wed Sep 27 12:44:09.925667 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/model/extension.py", line 112, in before_commit
[Wed Sep 27 12:44:09.925771 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     methodcaller('before_commit', session)
[Wed Sep 27 12:44:09.925844 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/model/extension.py", line 92, in notify_observers
[Wed Sep 27 12:44:09.925907 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     func(observer)
[Wed Sep 27 12:44:09.925984 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/model/modification.py", line 72, in before_commit
[Wed Sep 27 12:44:09.926070 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     self.notify(obj, domain_object.DomainObjectOperation.changed)
[Wed Sep 27 12:44:09.926142 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/model/modification.py", line 79, in notify
[Wed Sep 27 12:44:09.926214 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     observer.notify(entity, operation)
[Wed Sep 27 12:44:09.926286 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 114, in notify
[Wed Sep 27 12:44:09.926363 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     for resource in entity.resources:
[Wed Sep 27 12:44:09.926435 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]   File "/usr/lib/ckan/default/src/ckan/ckan/model/package.py", line 91, in resources
[Wed Sep 27 12:44:09.926519 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399]     assert len(self.resource_groups_all) == 1, "can only use resources on packages if there is only one resource_group"
[Wed Sep 27 12:44:09.926610 2017] [:error] [pid 70494:tid 140372650989312] [remote 157.140.16.90:5399] AssertionError: can only use resources on packages if there is only one resource_group
</code>

**Comment by benscott** [comment]
Duplicate resource group. Updated duplicate resource group state to deleted.
